#!/bin/bash
telnet https://www.google.com/url?sa=t&source=web&rct=j&url=https://rakuten.tv/uk/movies/star-wars-episode-iv-a-new-hope-extras&ved=2ahUKEwip4arO7dn7AhXDGewKHW5YAhwQwqsBegQIYRAE&usg=AOvVaw3LWGhr3mHePNhg-hZT4B8M
